serve:
  addr: "127.0.0.1:8081"
  name: "project-api"

zap:
  debugFileName: "D:\\github_project\\ginproject\\logs\\debug\\project-debug.log"
  infoFileName: "D:\\github_project\\ginproject\\logs\\info\\project-info.log"
  warnFileName: "D:\\github_project\\ginproject\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

etcd:
  addrs:
    - "127.0.0.1:2379"