serve:
  host: "127.0.0.1"
  port: ":80"

zap:
  debugFileName: "D:\\github_project\\ginproject\\logs\\debug\\project-debug.log"
  infoFileName: "D:\\github_project\\ginproject\\logs\\info\\project-info.log"
  warnFileName: "D:\\github_project\\ginproject\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

grpc:
  addr: "127.0.0.1:8080"
  name: "project-user"
  version: "v1"
  weight: 2

etcd:
  addrs:
    - "127.0.0.1:2379"